// 変数宣言
var startBtn = document.getElementById('start');
var isStart = false;
var roulette = document.getElementById('roulette');
var place = '';
var intervalID = -1;
var spotList = [];

// 行きたい場所を配列にぶち込む
spotList = [
    '<span>強そうな苗字</span>',
    '<span>便利なもの</span>',
    '<span>見て癒されるかわいいもの</span>',
    '<span>映画館で見て感動する映画</span>',
    '<span>冷蔵庫に入っているとテンションが上がるモノ</span>',
    '<span>異性の好きな仕草</span>',
    '<span>異性に言われて嬉しい言葉</span>',
    '<span>付き合って1年記念でセンスのあるデート場所</span>',
    '<span>異性から誕生日プレゼントで嬉しい贈り物</span>',
    '<span>（想像で）カップル間で秘密にしてる衝撃なこと</span>',
    '<span>面白いエピソード</span>',
    '<span>昔モテてそうな人</span>',
    '<span>将来お金持ちになりそうな人</span>',
    '<span>子だくさんになりそうな人</span>',
    '<span>秘密がありそうな人</span>',
    '<span>でできたら嬉しい夕飯</span>',
    '<span>楽しい旅行先</span>',
    '<span>お父さんの好きなところ</span>',
    '<span>好きなテレビ番組</span>',
    '<span>飼ってみたいペット</span>',
    '<span>ロマンチックな漫画・ゲームキャラ</span>',
    '<span>子供に読ませたい漫画・アニメ</span>',
    '<span>SNSのフォロワー数が多そうなキャラ</span>',
    '<span>兄弟にしたいキャラ</span>',
    '<span>モテそうなポケモン</span>',
    '<span>強そうな家具</span>',
    '<span>足の早そうな虫</span>',
    '<span>モテそうな祝日</span>',
    '<span>カッコいい都道府県</span>',
    '<span>背が高そうな乗り物</span>',
    '<span>面白い変顔</span>',
    '<span>キレのある動き</span>',
    '<span>きつい創作筋トレ</span>',
    '<span>有名なダンス</span>',
    '<span>子供の良くやってた動き</span>',
    '<span>お酒が美味しいシュチュエーション</span>',
    '<span>お洒落なお酒・カクテルの名前（創作OK）</span>',
    '<span>お酒に合うおつまみ</span>',
    '<span>お酒の失敗談</span>',
    '<span>気合の入れる飲み会</span>',
    '<span>カッコいい四字熟語</span>',
    '<span>有名な文庫</span>',
    '<span>お洒落な漢字</span>',
    '<span>イケてる英単語</span>',
    '<span>語彙力を感じる一言</span>',
    '<span>よく分からない数学単語（ベクトル、シグマ、積分など）</span>',
    '<span>ありそうな理科実験用具</span>',
    '<span>ワクワクする実験</span>',
    '<span>解剖したくない生物</span>',
    '<span>お洒落な星（星座）</span>',
    '<span>尊敬する歴史人物</span>',
    '<span>タイムスリップしたくない時代</span>',
    '<span>世界を変えた発明品</span>',
    '<span>イケメンな武将</span>',
    '<span>美人っぽい歴史人物</span>',
    '<span>行きたい観光地</span>',
    '<span>引っ越したい海外の国</span>',
    '<span>ステータスを感じる街・駅</span>',
    '<span>観光客が多そうな世界遺産</span>',
    '<span>持ちやすそうな形の都道府県</span>',
    '<span>良く見かける飲食店</span>',
    '<span>美味しそうな飲食店の店名（創作）</span>',
    '<span>人気店だなと思う店の特徴</span>',
    '<span>ついつい買ってしまう食べ物・飲み物</span>',
    '<span>意外な組み合わせの料理</span>',
    '<span>毎年楽しみなイベント</span>',
    '<span>年越ししたい場所</span>',
    '<span>クリスマスでもらって嬉しいプレゼント</span>',
    '<span>夏フェスで盛り上がりそうなバンド・アーティスト</span>',
    '<span>ハロウィンで意中の人に着て欲しいコスプレ</span>',
    '<span>もらって嬉しいファッションブランド</span>',
    '<span>買って失敗した洋服</span>',
    '<span>お金持ってそうだと思うアイテム</span>',
    '<span>彼氏・彼女が持っていたら嫌なファッションアイテム</span>',
    '<span>好きな髪型</span>',
    '<span>兄、姉になって欲しい有名人</span>',
    '<span>ついつい見てしまうYouTuber</span>',
    '<span>好きな作家</span>',
    '<span>憧れるスポーツ選手</span>',
    '<span>ドラマ出てると期待してしまう有名人</span>',
    '<span>便利な家具・家電</span>',
    '<span>一人暮らしに必要な家具・家電</span>',
    '<span>高そうな家具・家電</span>',
    '<span>もらって嬉しい家具・家電</span>',
    '<span>お洒落な家具・家電</span>',
    '<span>新婚旅行で行きたいところ</span>',
    '<span>ロマンチックなプロポーズ演出</span>',
    '<span>宇宙でやってみたいこと</span>',
    '<span>一度は言ってみたいセリフ</span>',
    '<span>ロマンチックな言葉</span>',
    '<span>老後まで楽しめそうな趣味娯楽</span>',
    '<span>カラオケで盛り上がる曲</span>',
    '<span>頭が良さそうな人の趣味</span>',
    '<span>お洒落な人が過ごしてそうな場所</span>',
    '<span>恋人と楽しみたい趣味娯楽</span>',
    '<span>モテる部活</span>',
    '<span>ルールが複雑なスポーツ</span>',
    '<span>マイナーなスポーツ</span>',
    '<span>子供に習わせたいスポーツ</span>',
    '<span>体育の授業で嬉しいスポーツ</span>',
    '<span>コンビニの商品の人気</span>',
    '<span>100円ショップの商品の人気</span>',
    '<span>飲食店の人気</span>',
    '<span>駅の人気</span>',
    '<span>中華料理の人気</span>',
    '<span>学校給食の人気</span>',
    '<span>有名人の人気</span>',
    '<span>子供に人気なもの</span>',
    '<span>アニメ・漫画のキャラの人気</span>',
    '<span>ゲームキャラの人気（モンスター含む）</span>',
    '<span>キャラクターの人気（ゆるキャラ含む）</span>',
    '<span>プレゼント・お土産の人気</span>',
    '<span>建物の人気</span>',
    '<span>住みたい国や場所の人気</span>',
    '<span>アプリ・ウェブサービスの人気</span>',
    '<span>乗り物の人気</span>',
    '<span>俳優の人気</span>',
    '<span>悪役の人気</span>',
    '<span>食べ物の人気</span>',
    '<span>飲み物の人気</span>',
    '<span>生き物の人気</span>',
    '<span>おもちゃの人気</span>',
    '<span>電化製品の人気</span>',
    '<span>映画の人気</span>',
    '<span>ミュージシャンの人気</span>',
    '<span>お菓子・スイーツ・アイスの人気</span>',
    '<span>ペットの人気</span>',
    '<span>職業の人気</span>',
    '<span>おにぎりの具の人気</span>',
    '<span>パンの種類の人気</span>',
    '<span>趣味の人気</span>',
    '<span>メーカー（ブランド）の人気</span>',
    '<span>アニメ・漫画の人気</span>',
    '<span>ゲームの人気</span>',
    '<span>和食料理の人気</span>',
    '<span>洋食料理の人気</span>',
    '<span>歴史上の人物の人気</span>',
    '<span>声優の人気</span>',
    '<span>童話の人気</span>',
    '<span>歌・曲の人気</span>',
    '<span>映画の登場人物の人気</span>',
    '<span>アスリートの人気</span>',
    '<span>スポーツの人気</span>',
    '<span>テレビ番組の人気</span>',
    '<span>恋人にしたい職業の人気</span>',
    '<span>デートスポットの人気</span>',
    '<span>ハネムーンで行きたい場所の人気</span>',
    '<span>酒のつまみ・居酒屋メニューの人気</span>',
    '<span>化粧品の人気</span>',
    '<span>ボードゲームの人気</span>',
    '<span>資格・免許の人気</span>',
    '<span>旅行したい国や場所の人気</span>',
    '<span>旅行先に持っていきたいもの</span>',
    '<span>ゾンビと戦うときに持っていきたいもの</span>',
    '<span>無人島に持っていきたいもの</span>',
    '<span>一人暮らしに必要なもの</span>',
    '<span>美しいもの</span>',
    '<span>こわいもの</span>',
    '<span>楽しいこと</span>',
    '<span>嬉しいこと</span>',
    '<span>カバンに入っていたら嬉しいもの</span>',
    '<span>言われて嬉しい言葉</span>',
    '<span>なりたい生き物</span>',
    '<span>なりたい歴史上の人物</span>',
    '<span>なりたい有名人</span>',
    '<span>なりたいキャラ</span>',
    '<span>生き物の大きさ</span>',
    '<span>学校にあるものの大きさ</span>',
    '<span>歴史上の人物の強さ</span>',
    '<span>映画の登場人物の強さ</span>',
    '<span>生き物の強さ</span>',
    '<span>アニメ・漫画のキャラの強さ</span>',
    '<span>ゲームキャラの強さ（モンスター含む）</span>',
    '<span>強そうな言葉（漢字、熟語など）</span>',
    '<span>強そうな効果音</span>',
    '<span>有名人の年収・資産</span>',
    '<span>重そうなもの</span>',
    '<span>ボードゲームの（物理的な）重さ</span>',
    '<span>食べ物のカロリー</span>',
    '<span>モテる条件・特技</span>',
    '<span>やわらかそうなもの</span>',
    '<span>カッコいいもの</span>',
    '<span>カッコいいセリフ</span>',
    '<span>カッコいい苗字・名前</span>',
    '<span>かわいいもの</span>',
    '<span>小学生が好きな言葉</span>',
    '<span>中高生が好きな言葉</span>',
    '<span>人生で大切なもの・こと</span>',
    '<span>雪山で遭難したときにもっていたいもの</span>',
    '<span>地球観光に来た宇宙人にあげたいお土産</span>',
    '<span>テンションが上がるもの・こと</span>',
    '<span>時代遅れの言葉</span>',
    '<span>オタクが喜ぶセリフ・設定</span>',
    '<span>グッとくる仕草・行動</span>',
    '<span>結婚したい有名人</span>',
    '<span>結婚したいキャラ</span>',
    '<span>親になってほしいキャラ</span>',
    '<span>ほしい特殊能力・武器</span>',
    '<span>便利なもの</span>',
    '<span>されたいプロポーズ</span>',
    '<span>旅先ですることの人気</span>',
    '<span>白米に合いそうなもの</span>',
    '<span>中学生になって考えよう カッコいいもの・こと</span>',
    '<span>鳥肌が立つこと</span>',
    '<span>1000円くらいまででできる楽しいこと</span>',
    '<span>桃太郎になって考えよう 頼りになる家来</span>',
    '<span>動物園にいる動物の人気</span>',
    '<span>男女がそれぞれ好きそうなもの</span>',
    '<span>祖父母になって考えよう 孫に言われたら嬉しい言葉</span>',
    '<span>ふだん聞く言葉の頻度</span>',
    '<span>破壊力のある言葉</span>',
    '<span>冷蔵庫になって考えよう 入れてほしいもの</span>',
    '<span>行事の人気</span>',
    '<span>宝箱をあけて入ってたら嬉しいもの</span>',
    '<span>幼稚園児になって考えよう テンションが上がるとき</span>',
    '<span>上に乗ってみたい動物</span>',
    '<span>商店街のくじの景品でランクが高いもの</span>',
    '<span>SNSを活用するにあたって大切なもの・こと</span>',
    '<span>夏に行きたい場所や国の人気</span>',
    '<span>「一生これしか食べられない」なら選びたい食べもの</span>',
    '<span>猫になって考えよう 心地のいい場所</span>',
    '<span>いい匂いのもの</span>',
    '<span>強そうな5文字</span>',
    '<span>芸人になって考えよう ヤバい罰ゲーム</span>',
    '<span>コンビニで買える食べ物の人気</span>',
    '<span>公園の石をどかしたとき、あったらビックリするもの</span>',
    '<span>小学生になって考えよう 嬉しいこと</span>',
    '<span>明るいもの</span>',
    '<span>言われたら嬉しいプロポーズの言葉</span>',
    '<span>探検家になって考えよう ワクワクする場所</span>',
    '<span>寿司ネタの人気</span>',
    '<span>動物の特徴でほしいもの</span>',
    '<span>お嬢様になって考えよう 優秀な執事</span>',
    '<span>人からごちそうされたい食べ物</span>',
    '<span>桃太郎の場面（お話のどのあたりか）（1:むかしむかし-100:めでたしめでたし）</span>',
    '<span>能力者になって考えよう ハデに使えそうな脳力</span>',
    '<span>海の生き物の人気</span>',
    '<span>冷蔵庫の中にあったらテンションが上がるもの</span>',
    '<span>高校生になって考えよう 授業中、起きたら大変なこと</span>',
    '<span>写真を撮りたくなるもの</span>',
    '<span>どうしてもこれだけは許せないということ</span>',
    '<span>幸せを感じること</span>',
    '<span>新婚旅行先の人気</span>',
    '<span>学校の先生に怒られそうなこと</span>',
    '<span>犬になって考えよう 嬉しいこと</span>',
    '<span>よく行く場所</span>',
    '<span>思わず見てしまうメールのタイトル</span>',
    '<span>ボディビルダーになって考えよう 言われたいかけ声</span>',
    '<span>生まれ変わったらなりたい動物</span>',
    '<span>大人っぽい言動</span>',
    '<span>動画配信者にとって必要な能力・資質</span>',
    '<span>家族にしてもらったら嬉しいこと</span>',
    '<span>ショックを受けた好きな人のクセ</span>',
    '<span>侍になって考えよう 尽くしたいタイプの人</span>',
    '<span>食べ物のやわらかさ</span>',
    '<span>突然の一日オフ。最高の過ごし方は？</span>',
    '<span>先生になって考えよう 卒業式に言われて嬉しい言葉</span>',
    '<span>幼いころにほしかったもの</span>',
    '<span>宇宙にいるときにやってみたい行動</span>',
    '<span>お笑い芸人にとって必要な能力・資質</span>',
    '<span>寝起きにしたいこと</span>',
    '<span>変顔の度合い（実際にやる）</span>',
    '<span>修学旅行生になって考えよう 行きたい旅行先</span>',
    '<span>部屋の中にある大切なもの</span>',
    '<span>痛い思い出（物理・精神どちらでも）</span>',
    '<span>生きる上で大切なもの・こと</span>',
    '<span>食べ物の辛さ</span>',
    '<span>カッコいいと思うエピソード</span>',
    '<span>就活中の大学生になって考えよう 働きたい職場</span>',
    '<span>聞こえてきたら嬉しい音</span>',
    '<span>厳しく無口な父に言われたら嬉しい言葉</span>',
    '<span>アイドル業にとって必要な能力・資質</span>',
    '<span>黒いもの</span>',
    '<span>卒業式で流したら感動する音楽や効果音</span>',
    '<span>魔法使いになって考えよう 使ってみたい魔法</span>',
    '<span>日常に起こるいいこと</span>',
    '<span>片思い中の好きな人に言われたら嬉しい言葉</span>',
    '<span>仕事をする上で必要な能力・資質</span>',
    '<span>眠くなるもの</span>',
    '<span>見た目が子供に戻ったならしたいこと</span>',
    '<span>馬主になって考えよう 速そうな馬の名前</span>',
    '<span>投げたいもの</span>',
    '<span>勇気ある行動</span>',
    '<span>芸能事務所の社長になって考えよう 所属芸能人が起こしたら大変な事件</span>',
    '<span>包まれたいもの</span>',
    '<span>砂漠で遭難したときにほしいもの</span>',
    '<span>超能力になって考えよう 友人の脳内を読んだらショックだった考え</span>',
    '<span>ずっと見ていられるもの</span>',
    '<span>死ぬまでにしたいこと</span>',
    '<span>ヒーローになって演じよう カッコいいポーズ</span>',
    '<span>なつかしさを感じるもの・こと</span>',
    '<span>テストでその点を取ったときの反応</span>',
    '<span>母になって考えよう 子供が寝言で言っていたら嬉しいこと</span>',
    '<span>便利なスマホアプリ</span>',
    '<span>叫ぶと必殺技っぽい言葉</span>',
    '<span>芸能人になって考えよう 「これドッキリじゃね？」と疑うできごと</span>',
    '<span>足の速い動物</span>',
    '<span>これは恋か愛か</span>',
    '<span>人間関係で必要な能力・資質</span>',
    '<span>おみやげにもらったら嬉しいもの</span>',
    '<span>奇跡の体験</span>',
    '<span>タイムトラベラーになって考えよう 過去から持って帰りたいもの</span>',
    '<span>朝ごはんに食べたいもの</span>',
    '<span>お尻から出てきたらビックリするもの</span>',
    '<span>科学者になって考えよう 発明したい薬</span>',
    '<span>踏んだら痛そうなもの</span>',
    '<span>SNSでめちゃくちゃいいねされそうな投稿</span>',
    '<span>人物やキャラクターのイメージ</span>',
    '<span>疲れたときにしたいこと</span>',
    '<span>あったらおいしそうなアイスクリームの味</span>',
    '<span>赤ちゃんになって考えよう 最高の瞬間</span>',
    '<span>家にある便利なもの</span>',
    '<span>5歳児が言ったらビックリする言葉</span>',
    '<span>魔王になって考えよう こんな勇者はイヤだ</span>',
    '<span>大学生が反応する言葉</span>',
    '<span>機嫌がいいときにしそうな行動</span>',
    '<span>リーダーにとって必要な能力・資質</span>',
    '<span>友達になりたい人の特徴</span>',
    '<span>人生の中で、やる回数が多いこと</span>',
    '<span>愛されていると思うこと</span>',
    '<span>アンパンマンがやっていたらショックなこと</span>',
    '<span>炎上しそうなこと</span>',
    '<span>バレバレなズル休みの言い訳</span>',
    '<span>2泊3日の旅行で忘れたら困るもの</span>',
    '<span>上司から言われたらキツいこと</span>',
    '<span>後輩から言われたらキツいこと</span>',
    '<span>バイト仲間から言われたらキツいこと</span>',
    '<span>先送りにしがちなこと</span>',
    '<span>ラッキーと思う出来事</span>',
    '<span>実際にあったらトラウマになりそうなこと</span>',
    '<span>イヤすぎる罰ゲーム</span>',
    '<span>疲労度を体の状態で表す</span>',
    '<span>学校で起こりうる最大のピンチ</span>',
    '<span>触るのが怖い虫</span>',
    '<span>イライラしてしまうこと</span>',
    '<span>2泊3日の旅行で忘れたら困るもの</span>',
    '<span>日常で起こりうる恥ずかしいこと</span>',
    '<span>緊張すること</span>',
    '<span>異性から言われたらキツイこと</span>',
    '<span>異性にドン引きしてしまう瞬間</span>',
    '<span>初デートで起こったら一気に気持ちが冷めてしまうそうなこと</span>',
    '<span>脈アリと思う瞬間</span>'
];

// スタートボタンを押したときの処理
function clickedStart() {
    'use strict';
    isStart = true;
    startBtn.disabled = true;
    intervalID = setInterval(function() {
        if(isStart === true) {
            place = spotList[Math.floor( Math.random() * spotList.length )];
            roulette.className = 'name';
            document.getElementById("isPlace").innerHTML = place;
        }
    }, 10);
}

// ストップボタンを押した時の処理
function clickedStop() {
    'use strict';
    clearTimeout(intervalID);
    startBtn.disabled = "";
    isStart = false;
    if(place === '') {
        alert("スタートボタンを押してからストップボタンを押してね！");
    } else {
// 結果を画面に表示
    roulette.className = 'name';
    document.getElementById("isPlace").innerHTML = place;
    }
}
